// JavaScript Document

mapofaverage = ["This map shows the average temperature. Areas that are hotter are darker red, and areas that are colder are in darker blue.","This map shows the average precipitation. Areas that are generally wetter are bluer, and areas that are generally drier are more yellow to red."]

historicalchange = ["This map shows the historical <b><i>rate of change</b></i> for temperature during 1951 - 2006. <b>These changes should be interpreted in conjunction with the map of statistical confidence.</b>  Areas that become warmer over time are yellow to red, and areas that become cooler over time are blue. We recommend that areas where there is low statistical confidence in this change (grey areas on map of statistical confidence) should not be used for making climate-related decisions.","This map shows the historical <b><i>rate of change</b></i> for precipitation during 1951 - 2006. <b>These changes should be interpreted in conjunction with the map of statistical confidence.</b>  We recommend that areas where there is low statistical confidence in this change (grey areas on map of statistical confidence) should not be used for making climate-related decisions."]

historicalsig = ["This map shows the statistical confidence of temperature change during 1951 - 2006. <b>Areas with higher statistical confidence in change are in darker purple</b>, and tan areas are marginally significant (0.05 - 0.10).  Grey areas have low statistical confidence in change.","This map shows the statistical confidence of precipitation change during 1951 - 2006. <b>Areas with higher statistical confidence in change are in darker purple</b>, and tan areas are marginally significant (0.05 - 0.10).  Grey areas have low statistical confidence in change."]

ghistoricalchange = ["This map shows the historical <b><i>rate of change</b></i> for temperature during 1951 - 2001. <b>These changes should be interpreted in conjunction with the map of statistical confidence.</b> We recommend that areas where there is low statistical confidence in this change should not be used for making climate-related decisions.","This map shows the historical <b><i>rate of change</b></i> for precipitation during 1951 - 2001. <b>These changes should be interpreted in conjunction with the map of statistical confidence.</b> We recommend that areas where there is low statistical confidence in this change should not be used for making climate-related decisions."]

ghistoricalsig = ["This map shows the statistical confidence of temperature change during 1951 - 2001. <b>Areas with higher statistical confidence in change are in darker purple</b>, and tan areas are marginally significant (0.05 - 0.10). Grey areas have low statistical confidence in change.","This map shows the statistical confidence of precipitation change during 1951 - 2001. <b>Areas with higher statistical confidence in change are in darker purple</b>, and tan areas are marginally significant (0.05 - 0.10). Grey areas have low statistical confidence in change."]

futurechange = ["This map shows the temperature change projected by the climate model [GCM Name] run under the [Scenario Name] scenario for [startYr] - [endYr] as compared to 1961 - 1990. <b>Note that this is only one model, and may be different from other models. We recommend using <i>ensemble analysis</i></b> to find consensus between and see the range of projected changes across all 16 models. Areas that are changing to become warmer over time are yellow to red, and areas that are changing to become cooler over time are blue.","This map shows the precipitation change projected by the climate model [GCM Name] run under the [Scenario Name] scenario for [startYr] - [endYr] as compared to 1961 - 1990. <b>Note that this is only one model, and may be different from other models. We recommend using <i>ensemble analysis</i></b> to find consensus between and see the range of projected changes across all 16 models. Areas that are changing to become wetter over time are green to blue, and areas that are changing to become drier over time are yellow to red."]

tempensemble = ["0%: This map shows the smallest temperature change projected by any of the climate models. Thus, <b>the ensemble of models project future temperature increase will be at least this great</b>, and 15 of the 16 models project even greater temperature increases."," 20%: This map shows the temperature change where <b>80% of the climate models project a greater temperature increase</b>, and 20% of the climate models project less of a temperature increase. Thus, 12 of the 16 models project higher future temperatures than this, and 3 of the 16 models project lower temperatures.","40%: This map shows the temperature change where <b>60% of the climate models project a greater temperature increase</b>, and 40% of the climate models project less of a temperature increase. Thus, 9 of the 16 models project higher future temperatures than this, and [6] of the 16 models project lower temperatures.","60%: This map shows the temperature change where <b>60% of the climate models project less of a temperature increase</b>, although 40% of the climate models project an even greater temperature increase. Thus, 9 of the 16 models project lower future temperatures than this, but 9 of the 16 models project higher temperatures than this.","80%: This map shows the temperature change where <b>80% of the climate models project a lower temperature change</b>, although 20% of the climate models project an even greater temperature change. Thus, 12 of the 16 models project lower future temperatures, but 3 of the 16 models project higher temperatures.","100%: This map shows the largest temperature change projected by any of the climate models.  Thus, <b>the ensemble of models project the future temperature increase will be at most this great</b>, and 15 of the 16 models project less of a temperature increase.","50%: This map shows the temperature change projected by the middle model. That is, <b>half of the models project a greater amount of change, and half of the models project less change</b> as compared to the 1961-1990 baseline average."]

precipensemble = ["0%: This map shows change projected by the model with the lowest amount of precipitation. <b>Areas that are blue had complete agreement between all models that precipitation will increase.</b> Areas that are yellow to red represent the largest decrease in precipitation projected by any of the models.","20%: This map shows the areas where 80% of the model agree on greater precipitation increase. <b>If the area is blue then at least 80% of the models agree that precipitation will increase.</b> Areas that are yellow to red had 3 of the 16 models projecting an even greater decrease in precipitation.","40%: This map shows the temperature change where 60% of the climate models project a greater temperature increase, and 40% of the climate models project less of a temperature increase. <b>If the area is blue then at least 60% of the models agree that precipitation will increase.</b> Areas that are yellow to red had 6 of the 16 models projecting an even greater decrease in precipitation.","60%: This map shows the temperature change where 60% of the climate models project less precipitation, and 40% of the climate models project greater precipitation. <b>If the area is yellow to red then at least 60% of the models agree that precipitation will decrease.</b> Areas that are blue had 6 of the 16 models projecting an even greater increase in precipitation.","80%: This map shows the temperature change where 80% of the climate models project less precipitation, and 20% of the climate models project greater precipitation. <b>If the area is yellow to red then at least 80% of the models agree that precipitation will decrease.</b> Areas that are blue had 3 of the 16 models projecting an even greater increase in precipitation.","100%: This map shows change projected by the model with the greatest amount of precipitation. <b>Areas that are yellow to red had complete agreement between all models that precipitation will decrease.</b> Areas that are blue represent the largest increase in precipitation projected by any of the models.","50%: This map shows the precipitation change projected by the middle model. <b>Areas that are blue are projected to increase by at least half of the models, and areas that are yellow to red are projected to decrease in precipitation by at least half of the models.</b>"]

