// JavaScript Document

factoids = [{desc:"China Academy of Science reported that annual rainfall in the area of the Yangtze River had dropped 10.3 and 6.9 percent respectively in 2006 and 2007 due to climate change.  Additionally, severe droughts in 2007 and 2008 resulted in the shrinking of two of the nation's biggest freshwater lakes, Poyang and Dongting.",
			hlink:"http://www.nature.org/wherewework/asiapacific/china/work/yangtze.html",
			reference:"http://www2.chinadaily.com.cn/china/2009-04/20/content_7693329.htm",
			credit:"Photo © CJ Hudlow/ TNC",
			lat:33.468028,
			lon:91.195903,
			icon:"rain.png"},
			{desc:"Expected increased climate variability will cause the area of the Zambezi River to experience extremes in drought and flooding.  Unpredictable cyclones and storms have grown in severity in the past several years wiping out crop lands and villages that historically have not been effected.  Additionally, when there is a lack of precipitation, river flows decrease which will only exacerbates the ecological challenges dams have caused.",
			hlink:"http://www.nature.org/wherewework/africa/wherewework/art25447.html",
			reference:"",
			credit:"Photo © Patrick McCarthy/TNC",
			lat:-16.250392,
			lon:23.239825,
			icon:"rain.png"},
			{desc:'Zambia is a country already seeing the effects of climate change through elongated droughts which intern shortens the growing season of staple crops.  The Global Environmental Facility predicts that "areas suitable for staple crops such as maize are likely to fall by more than 80 percent."',
			hlink:"http://thegef.org/uploadedfiles/LDCF/LDCF_insert_Zambia.pdf",
			reference:"",
			credit:"Photo ©Tim Boucher/TNC",
			lat:-14.446922,
			lon:27.652514,
			icon:"deserts.png"},
			{desc:'Increasing temperatures and desertification has aided in the 90 percent reduction of Lake Chad’s water and a 3 kilometer annual loss of land to the Sahara desert.  The lake provides drinking water for 30 million people located in Chad, Niger, Nigeria and Cameroon.',
			hlink:"http://allafrica.com/stories/200905210326.html",
			reference:"",
			credit:"Photo by © Shashank Bengali/ McClatchy Newspapers",
			lat:13.503619,
			lon:13.775036,
			icon:"deserts.png"},
			{desc:"China Academy of Science reported that annual rainfall in the area of the Yangtze River had dropped 10.3 and 6.9 percent respectively in 2006 and 2007 due to climate change.  Additionally, severe droughts in 2007 and 2008 resulted in the shrinking of two of the nation's biggest freshwater lakes, Poyang and Dongting.",
			hlink:"http://www.nature.org/wherewework/asiapacific/china/work/yangtze.html",
			reference:"http://www2.chinadaily.com.cn/china/2009-04/20/content_7693329.htm",
			credit:"",
			lat:33.468028,
			lon:91.195903,
			icon:"rain.png"},
			{desc:"An IUCN report shows climate models that predict an increase in monsoon precipitation by 11 and 20 percent by 2030in Bangladesh.  This will lead to surface runoff to increase by 20 to 45 percent.  Also and an additional 14.3 percent of the country will become extremely vulnerable to floods, while the already flood-vulnerable areas will face higher levels of flooding.",
			hlink:"http://thegef.org/uploadedfiles/LDCF/LDCF_insert_Bangladesh.pdf",
			reference:"http://www.nlcap.net/fileadmin/NCAP/Countries/Bangladesh/NCAP_workplan_Bangladesh_summary.01.170106.pdf",
			credit:"",
			lat:23.795319,
			lon:90.345369,
			icon:"rain.png"},
			{desc:"One fifth of the world's coral reefs have already died and those found in the Asian Indian Ocean are most at risk with 54 percent either lost or endangered. Climate change plays a significant role in this destruction by raising sea level, temperature and acidity.   Scientists estimate we could lose up to 70 percent of our planet’s coral reefs over the next 50 years.",
			hlink:"http://www.nature.org/wherewework/asiapacific/coraltriangle/howwework/",
			reference:"http://www.worldwatch.org/node/6044",
			credit:"Photo by © Mark Godfrey/TNC",
			lat:7.642231,
			lon:134.710928,
			icon:"marine.png"},
			{desc:"The Kalamurina region of Australia is considered one of five last great wild places on Earth; however climate change is estimated to reduce rainfall between 5 and 10 percent by 2050, changing the ecosystem’s food and water supply.  This affects the wildlife population with 15 percent of reptiles, 20 percent of mammals, and 500 vascular plants currently listed as endangered or vulnerable.",
			hlink:"http://www.nature.org/wherewework/asiapacific/australia/features/kalamurina.html",
			reference:"http://www.australianwildlife.org/",
			credit:"Photo by © Australian Wildlife Conservancy and Wayne Lawler/EcoPix",
			lat:-27.537597,
			lon:137.182256,
			icon:"climatechange.png"},
			{desc:"Mangroves are the most degraded forest habitats in the world and climate change threatens to make this situation worse.  The 2007 IPCC report estimates an 18 cm to 59 cm increase in sea level by 2100.  According to UNEP, this could lead to a 12 percent reduction of all mangrove forests in the Pacific.  Additionally, once a temperature of 25 °C (77 °F) is reached mangrove growth ceases because of thermal stress.  When temperatures increase to 38 °C (100 °F) the trees begin to die.",
			hlink:"http://maindb.unfccc.int/public/adaptation/adaptation_casestudy.pl?id_project=154",
			reference:"http://www.fao.org/newsroom/en/news/2008/1000776/index.html,http://data.iucn.org/dbtw-wpd/edocs/2006-041.pdf",
			credit:"Photo by © Mark Godfrey/TNC",
			lat:13.578653,
			lon:100.9493,
			icon:"marine.png"},
			{desc:"It is estimated that the Rio Bravo Conservation and Management Area project in the Mayan Forest will reduce, avoid, or mitigate up to 8.8 million tons of carbon dioxide over the next 40 years by preventing deforestation and ensuring sustainable forest management.",
			hlink:"http://www.nature.org/initiatives/climatechange/work/art4247.html",
			reference:"http://www.fao.org/newsroom/en/news/2008/1000776/index.html,http://data.iucn.org/dbtw-wpd/edocs/2006-041.pdf",
			credit:"Photo by © Gary Braasch/TNC",
			lat:17.720261,
			lon:-88.865422,
			icon:"forests.png"},
			{desc:"Noel Kempff Mercado is designed to simultaneously address climate change, conserve biodiversity and bring sustainable benefits to local communities. By avoiding logging and agricultural conversion, the project is expected to prevent the release of up to 5.8 million tons of carbon dioxide over the next 30 years.",
			hlink:"http://www.nature.org/initiatives/climatechange/work/art4253.html",
			reference:"",
			credit:"Photo by © Hermes Justiniano/TNC",
			lat:-14,
			lon:-61,
			icon:"forests.png"},
			{desc:"A study in Nature GeoScience found that 85% of the Amazon rainforests will die if temperatures increase by 4 °C.  With current climate trends of increasing temperatures causing drought and fires, as well as deforestation, more than half the Amazon will be damaged in 20 years.",
			hlink:"http://www.nature.org/wherewework/southamerica/brazil/work/art5079.html",
			reference:"http://www.mongabay.com/",
			credit:"Photo by © Scott Warren/TNC",
			lat:-7.013881,
			lon:-61.555211,
			icon:"forests.png"},
			{desc:"Climate Change Scientists at the Nature Conservancy report the mean annual temperatures in New Mexico have increased 0.6 °F per decade, with an overall change of 1.8° F since 1976.  This puts an extreme strain on the ecosystem and threatens its wildlife such as the black-tailed prairie dog and many migratory birds.",
			hlink:"http://www.nature.org/wherewework/northamerica/states/newmexico/press/press3539.html",
			reference:"",
			credit:"Photo by © Harold E. Malde/TNC",
			lat:34.972731,
			lon:-105.032364,
			icon:"climatechange.png"},
			{desc:"Coral reefs are extremely vital to the health and biodiversity of fisheries which ultimately supports the costal communities’ livelihoods.  However, coral reefs are one of the most threatened marine systems in the world.   Between 1996 and 2005, Southern Florida had lost almost 45 percent of its coral cover.",
			hlink:"http://www.nature.org/wherewework/northamerica/states/florida/preserves/art17499.html",
			reference:"",
			credit:"Photo by © Ken Nedimyer/TNC",
			lat:24.829228,
			lon:-80.82445,
			icon:"marine.png"},
			{desc:"Some models predict the Albemarle Peninsula in North Carolina will lose as much as 1 million acres to rising sea level in the next 100 years.  The effects are already visible evidence of rise in sea level on the peninsula with saltwater pushing into inland waterways and over farm fields.",
			hlink:"http://www.nature.org/initiatives/climatechange/work/art26197.html",//,http://www.coastalresilience.org/",
			reference:"",
			credit:"Photo by ©Erika Nortemann/TNC",
			lat:36.155539,
			lon:-76.044242,
			icon:"marine.png"},
			{desc:"Over the last century, Mid-Atlantic coastal areas have seen 5 to 6 inches more in sea level rise than the global average along the Mid-Atlantic.  It is estimated that by 2100, the northeastern coast will rise by between 12 to 20 inches more than other coastal areas.  This greatly endangers the ecosystem as well as the 8 million people living on the watershed.",
			hlink:"http://www.nature.org/wherewework/northamerica/states/connecticut/preserves/art22584.html",
			reference:"",
			credit:"Photo by © Jerry and Marcy Monkman/EcoPhotography.com",
			lat:41.050078,
			lon:-72.773414,
			icon:"marine.png"},
			{desc:"According to the National Academy of Sciences, 60 percent of prime land for cultivating grapes will be lost by the end of the century due to rising temperatures.  This will be largely felt in California since the state accounts for 90 percent of the country’s wine grape production.",
			hlink:"",
			reference:"http://www.econ.ucsb.edu/~olivier/media/cct_012307.htm",
			credit:"Photo by © Jerry and Marcy Monkman/EcoPhotography.com",
			lat:38.259328,
			lon:-122.288861,
			icon:"agriculture.png"},
			{desc:"Across the Appalachian region, average temperatures have risen more than 1.5 °F; winter average temperatures by 4 °F.  Northeast forests will become drier and more susceptible to fire as the planet warms, most likely changing the dense Appalachian forests in Pennsylvania and West Virginia to become more savanna-like.",
			hlink:"http://www.nature.org/wherewework/northamerica/states/centralappalachians/projects/art25020.html",
			reference:"",
			credit:"Photo by © The Nature Conservancy",
			lat:38.8643,
			lon:-79.628875,
			icon:"forests.png"},
			{desc:"Arctic habitats of Alaska and northwestern Canada have experienced some of the greatest temperature increases on the planet over the last 100 years with an increase of 5°C. Models suggest that by 2080, arctic sea ice will completely disappear during the summer months with ice melting by nearly 10 percent a decade.",
			hlink:"http://www.nature.org/initiatives/climatechange/features/art26189.html",
			reference:"http://www.nature.org/wherewework/northamerica/states/alaska/files/climatebro_ak_finala.pdf,http://www.nature.org/wherewework/northamerica/states/alaska/preserves/art26563.html",
			credit:"Photo by © Elson Lagoon/Dr. Jeff Masters' WunderBlog",
			lat:65.732033,
			lon:-152.42735,
			icon:"climatechange.png"},
			{desc:"The Gurschen Glacier that provides snow cover for the Gemsstock Mountain at the Andermatt ski resort in Switzerland has receded 20 meters in the past 15 years.  This is common across the Alps as rising temperatures have endangered ski resorts which play a major role in some country’s tourism sector.   Over the next 100 years, the alpine region is expected to lose 60 percent of its ice mass.",
			hlink:"http://www.landolt.com/wEnglish/infobox/news/2005_05_10_andermatt.asp",
			reference:"http://www.bookofjoe.com/2005/06/glacier_blanket.html",
			credit:"Photo by © Elson Lagoon/Dr. Jeff Masters' WunderBlog",
			lat:46.674603,
			lon:8.654672,
			icon:"climatechange.png"}]






